#!/bin/bash

#Login as root
exec sudo -i

#Try configuring unconfigured packages
dpkg --configure -a

#Update the contents of the repositories
apt-get update

#Try to fix missing dependencies
apt-get -f install

#Update the system
apt-get dist-upgrade

#Reinstall Ubuntu Desktop
apt-get install --reinstall ubuntu-desktop

#Remove Unnecessary packages
apt-get autoremove

#Delete downloaded packages already installed
apt-get clean

#Reboot the system
reboot
